name: Angular UTC

on:
  push:
    branches:
      - main # Adjust the branch name as needed
  pull_request:
    branches: [main]      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
      
    - name: Install dependencies
      run: npm install

    - name: Angular UTC
      run: ng test

    # Add additional steps as needed, such as running tests, deploying, etc.
